#include "Land.h"

//constructor
//there did not initialize any building is because the player does not own building at the beginning
Land::Land()
{
}

//Destructor
Land::~Land()
{

}

//player will add the building into the Custom ADT(Land)
void Land::add(string bName, int bCost, int bIncome, Building*& top, Building*& next)
{
	//if this is the first building the player brought, it is without the next address
	if (next == nullptr)
	{
		Building* newNode = new Building(bName, bCost, bIncome);
		top = newNode;
	}
	//except for the first building, the rest will have the address of next building
	else if (next != nullptr)
	{
		Building* newNode = new Building(bName, bCost, bIncome, next);
		top = newNode;
	}
	
}

//calculate the total income generated by building and add them into player's money
int Land::totalIncome()
{
	Building* Index;
	int total = 0;
	Index = this->sBuilding;
	while (Index != nullptr)
	{
		total += Index->getIncome();
		Index = Index->next;
	}
	return total;
}