#pragma once
#include <iostream>
#include "Building.h"
using namespace std;

//Custom Abstract Data Type, used to store the building
class Land
{
private:
	
public:
	Building* sBuilding; //allow to access building pointer without going through getter
	//Constructor
	Land();
	//Destructor
	~Land();
	//player will buy the building from shop and add it into the Custom ADT(Land)
	void add(string bName, int bCost, int bIncome, Building*& top, Building*& next);
	//calculate the total income generated by those building
	int totalIncome();
};