#pragma once
#include <iostream>
#include "Human.h"
#include "Player.h"
using namespace std;

//forward declaration
class Player;

//derived class, it inherits from parent class Human
class Worker : public Human
{
private:
	int workCost;	//show the cost of the worker
	int workIncome;	//show the income generated by the worker
public:
	//Constructor
	Worker();
	Worker(string wName, int wCost, int wIncome);
	//Destructor
	~Worker();

	//getters and setters
	int getCost();
	int setCost(int wCost);
	int getIncome();
	int setIncome(int wIncome);

	//allow worker work for player
	void work(Player*& player);

	//visitor deisng pattern, allow worker to accept the visitor pointer
	virtual void accept(Visitor& v);
	
	//prototype deisng pattern, allow worker to clone himself
	Human clone() override;
};